name: Deploy Function
            
on:
  workflow_run:
    workflows: ["Test Deno Module"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: fwvowwobldcklheidiwy

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1.2.0
        with:
          version: latest

      - run: supabase functions deploy --project-ref $PROJECT_ID