name: Test Deno Module

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2

      - name: Use Deno Version 1.8.2
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.8.2"

      # - name: Lint Deno Module
      #   run: deno fmt --check

      - name: Build Supabase Functions
        run: deno run --no-check ./supabase/functions/ai-chat/index.ts
        run: deno run --no-check ./supabase/functions/ai-quote/index.ts
        run: deno run --no-check ./supabase/functions/ai-scheduling/index.ts
        run: deno run --no-check ./supabase/functions/apple-calender-sync/index.ts
        run: deno run --no-check ./supabase/functions/google-calender-sync/index.ts
        run: deno run --no-check ./supabase/functions/openai-completion/index.ts
        run: deno run --no-check ./supabase/functions/rescheduling/index.ts

      - name: Test Supabase Functions
        run: deno test --allow-none
