name: Test Deno Module

on: 
  push:
    branches: 
      - '**' 
  pull_request:
    branches: 
      - '**' 

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  PROJECT_ID: fwvowwobldcklheidiwy

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2

      - name: Use Deno Version
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.8.2"

      - name: Upgrade to recent Version
        run: deno upgrade

      # - name: Lint Deno Module
      #   run: deno fmt --check

      - name: Compile Function 1
        run: deno compile --allow-net ./supabase/functions/ai-chat/index.ts

      - name: Compile Function 2
        run: deno compile --allow-net ./supabase/functions/ai-quote/index.ts

      - name: Compile Function 3
        run: deno compile --allow-net ./supabase/functions/ai-scheduling/index.ts

      - name: Compile Function 4
        run: deno compile --allow-net ./supabase/functions/apple-calender-sync/index.ts

      - name: Compile Function 5
        run: deno compile --allow-net ./supabase/functions/google-calender-sync/index.ts

      - name: Compile Function 6
        run: deno compile --allow-net ./supabase/functions/openai-completion/index.ts

      - name: Compile Function 7
        run: deno compile --allow-net ./supabase/functions/rescheduling/index.ts

      - name: Test Functions
        run: deno test --allow-none

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1.2.0
        with:
          version: latest

      - run: supabase functions deploy --project-ref $PROJECT_ID
